server:
  port: 8088

spring:
  application:
    name: 'auth'
        
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always

app:
  security:
    jwt:
      secret: testSuperSecret
      expirationMs: 86400000
      
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    
hystrix:
  shareSecurityContext: true  